name: Bug Report
description: Report a bug you've found
labels: "bug"
body:
- type: markdown
  attributes:
    value: |
      ![logo](https://raw.githubusercontent.com/EthanThatOneKid/acmcsuf.com/main/static/assets/about-illustration.svg)
- type: textarea
  attributes:
    label: What happened?
    description: |
      Can you please explain what happened, what you saw, what you expected to see, and any other relevant information? Please drag and drop any screenshots here.
    placeholder: Type away! Feel free to drag-and-drop any screenshots here.
  validations:
    required: false
