name: Bug Report
description: Report a bug you've found
title: "[BUG]: "
labels: "bug"
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the fime to fill out this bug report!
- type: textarea
  attributes:
    label: What happened?
    description: Can you please explain what happened, what you saw, what you expected to see, and any other relevant information?
    placeholder: Type away!
  validations:
    required: false
